### ISSUE TITLE
Add Android API conformance checks to build?

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-android#15]
Isn't there tooling that can be wired into a build pipeline to help ensure API level (version) conformance? 

I am blanking on the name. We should use that.

**Comment by LikeTheSalad** [comment]
I think for the current android lib subproject we should be covered already with android lint checks which should raise compile warnings (or errors, don't remember exactly) whenever we want to write some code that's not compatible with the `minSdk` value. For plain java lib subprojects we should use animal sniffer.

**Comment by LikeTheSalad** [comment]
I'm closing this issue since at the moment the only subproject we have is of type [Android library](https://developer.android.com/studio/projects/android-library) which already has a mechanism to raise compilation errors in case it detects that we added some code that's incompatible with the minimum Android API version defined in `instrumentation/build.gradle.kts`.

If we add "plain Java lib" subprojects later on, we'll have to add `animal sniffer` to those.
