### ISSUE TITLE
DatadogExporter for opentelemtry java/android

### ISSUE THREAD

**Issue by skymansandy** [open-telemetry/opentelemetry-android#236]
Does opentelemetry java/android have DatadogExporter? 

I'm referring to Swift exporter and [its example](https://github.com/open-telemetry/opentelemetry-swift/tree/main/Sources/Exporters/DatadogExporter
)

Want to explore similar thing in Android. Any help is greatly appreciated.

**Comment by breedx-splk** [comment]
Hi @skymansandy thanks for the question.

No, that doesn't exist, and probably shouldn't. One of the fundamental goals of OpenTelemetry is to provide vendor agnostic standards and implementations. Because OpenTelemetry has its own standardized, open format and protocol, I think it would be unlikely that this will be created. If it did exist, I think that opentelemetry-java-contrib would likely be the home for it. It's one of the few places where vendor-specific implementations are allowed.

You should also consider whether or not your vendor (in this case DataDog) supports OTLP as an ingest format. Most of the vendors either support OTLP now or will soon.

**Comment by skymansandy** [comment]
@breedx-splk thank you for the answer.

So does that mean there is no way android client can use an exporter implementation of datadog to export logs collected by opentelemetry? like the swift example: (https://github.com/open-telemetry/opentelemetry-swift/tree/main/Examples/Datadog%20Sample)

**Comment by breedx-splk** [comment]
@skymansandy No problem. 

There might be a way to do what you're describing, we just won't be able to support use cases that involve a specific vendor's implementation without direct help/support from that vendor. It's my understanding that some leeway/flexibility was afforded in the Swift case because DD was the main contributor/maintainer. Sorry I don't have much more to offer there right now.

**Comment by jack-berg** [comment]
Datadog is welcome to contribute a vendor specific exporter to [opentelemetry-java-contrib](https://github.com/open-telemetry/opentelemetry-java-contrib), or publish their own artifacts which implement the plugin extension interfaces for exporting (SpanExporter, MetricExporter, LogRecordExporter). 

Alternatively, the collector contrib repository has a [datadog exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/datadogexporter). Can export data first from android to a collector, and from the collector to datadog with the datadog exporter.

@skymansandy you'll want to a contact at datadog to get their recommendation on how best to accomplish this.
