### ISSUE TITLE
Demo example

### ISSUE THREAD

**Issue by NatanCoralogix** [open-telemetry/opentelemetry-android#444]
Hi,

any way to get a good demo example?
in the current demo nothing really happens, the NetworkChangeInstrumentation is not applied, no examples of how to use it,
same for crash, anr etc. how do i capture them with a custom exporter??

any example is welcome
thanks

**Comment by breedx-splk** [comment]
Hey @NatanCoralogix . The demo app here is very much a work in progress. There are a few other issues to add functionality (you can look for the demo-app label), including more rich browsing of "products" in the store, building a cart, etc. 

As you noticed, much of the existing instrumentation is missing. This is partially due to the demo-app being young, but also due to a notable refactoring of all instrumentation.

**Comment by breedx-splk** [comment]
@NatanCoralogix strongly encourage you to try again with the latest HEAD of the main branch. Things are shaping up now and hopefully instrumentation is working again for you. Please let us know! Thanks.
