### ISSUE TITLE
OtelRumConfig().setGlobalAttributes does not query the attribute supplier on every span or log creation

### ISSUE THREAD

**Issue by jpmuedano** [open-telemetry/opentelemetry-android#670]
Hello :) @LikeTheSalad 

Based on the guidance given in issue #625, my understanding is that the `OtelRumConfig().setGlobalAttributes {}` should query the `Supplier<Attributes>` on every span or log creation & populate the span attributes without having to explicitly set all attributes to every span through the `SpanBuilder.setAllAttributes()`. 

For Example, the `OtelRumConfig()` : 
```
        val config = OtelRumConfig()
            .setDiskBufferingConfiguration(diskBufferingConfig)
            .setGlobalAttributes { attributesSupplier.get() }
```
Where the supplier is a simple implementation including a setter:
```
public interface GlobalAttributeSupplier : Supplier<Attributes> {
    public fun set(attributes: Attributes)
}

public class GlobalAttributeSupplierImpl : GlobalAttributeSupplier {

    private var attributes: Attributes = Attributes.empty()

    public override fun set(attributes: Attributes) {
        this.attributes = attributes
    }

    override fun get(): Attributes = attributes

}
```
> The goal is to be able to update the attribute supplier & add/modify attributes during the application lifetime. 

Currently with this approach, I am not seeing the attributes populated on newly created spans, instead I have to include the attributes on every span builder to see the attributes reflected on every trace. I might be missing some other configuration for the global attribute supplier to work?

**Comment by LikeTheSalad** [comment]
Hi @jpmuedano 

It seems like this could be related to a memory visibility issue. I'd recommend annotating your class' `private var attributes: Attributes` field with `@Volatile` as shown below:

```kotlin
public class GlobalAttributeSupplierImpl : GlobalAttributeSupplier { 

  @Volatile /* Add this annotation to ensure that your changes to this field are visible from another thread */
  private var attributes: Attributes = Attributes.empty()

  /* ... */
}
```

Also, I'd recommend to pass your supplier directly to the `OtelRumConfig()` setter:

```kotlin
// Instead of this
val config = OtelRumConfig(
            .setGlobalAttributes { attributesSupplier.get() }

// Try this
val config = OtelRumConfig(
            .setGlobalAttributes(attributesSupplier)
```

It's not a big deal, so you can leave it as is if you like, is just that when you use `{ attributesSupplier.get() }` you're essentially wrapping your supplier within another one, which is not needed.

I hope it helps!

**Comment by JacekPietrasSpotOn** [comment]
Hello @LikeTheSalad 
Checked `@Volatile` and it didn't help. I see that yesterday @jpmuedano made progress, I will quote him:

> By design the `OtelRumConfig()` accepts a `Supplier<Attributes>`, but only the `AttributeKey<T>` and value are dynamic if set upon configuration. With this in mind, I successfully tested the scenario where the `globalAttributeKeys: List<String>` are set by the client application beforehand. If that is true, the supplier will be queried on every span & log. As long as we update the supplier, the predefined global attributes value becomes dynamic.

**Comment by LikeTheSalad** [comment]
Can you provide more details on how is everything set up? (not just the `OtelRumConfig` object). This object needs to be created before initializing the RUM object (which is done via OpenTelemetryRum.builder(app, config).build()). That process is done once, but if you keep your supplier handy after this process, any changes you make to it should be reflected in the logs.

To provide more context, the supplier that is provided in `OtelRumConfig` ends up in this [processor](https://github.com/open-telemetry/opentelemetry-android/blob/4fd360c9be69d050857178c1a96f9a0ef0a938f3/core/src/main/java/io/opentelemetry/android/internal/processors/GlobalAttributesLogRecordAppender.kt#L14) where it's queried on every `LogRecordBuilder.emit()` call. Now, maybe some other operation made during the RUM initialization could override this behavior, which is why I think we're going to need more details to provide more useful feedback.

**Comment by JacekPietrasSpotOn** [comment]
High level structure:
```kotlin
class OpenTelemetryClient(
    application: Application,
) {

    val openTelemetry: OpenTelemetry
    val attributeSupplier = GlobalAttributeSupplierImpl()

    init {
        // definition of attributes
        attributeSupplier.createInitialAttributesWithKey(
            listOf(
                "dynamic_property",
            ),
        )
        val config = OtelRumConfig()
            .setGlobalAttributes { attributeSupplier.get() }
            // ...

        val rumBuilder = OpenTelemetryRum.builder(application, config)
            // ...

        openTelemetry = rumBuilder
            .build()
            .openTelemetry
            .run(GlobalOpenTelemetry::set)
    }

    fun updateDynamicProperty(value: Int) {
        // declaration of attribute
        attributeSupplier.update("dynamic_property", value)
    }
}
```

And the key operations on attributes:
```kotlin
override fun createInitialAttributesWithKey(keys: List<String>) {
    attributes = Attributes.builder()
        .putAll(keys.associateWith { "" })
        .build()
}
override fun update(key: String, value: String) {
    val tempAttributes: MutableMap<String, Any> = mutableMapOf()
    attributes.forEach { k, v ->
        tempAttributes[k.key] = v
    }
    tempAttributes[key] = value
    set(
        Attributes.builder()
            .putAll(tempAttributes)
            .build(),
    )
}
```

**Comment by LikeTheSalad** [comment]
I've just tested it using our OTel demo app and I couldn't reproduce the issue. I've created [this branch](https://github.com/LikeTheSalad/opentelemetry-android/tree/global-attrs-test) with my changes in case you'd like to take a look at how it was all set up. I'll explain the details below:

I replicated your classes `GlobalAttributeSupplier` and `GlobalAttributeSupplierImpl` to make my test as similar as possible to your use case, with some minor changes to adjust to our demo app. You can find them [here](https://github.com/LikeTheSalad/opentelemetry-android/tree/global-attrs-test/demo-app/src/main/java/io/opentelemetry/android/demo/globalattrs) for more details.

I then used those classes when initializing the RUM client [here](https://github.com/LikeTheSalad/opentelemetry-android/blob/global-attrs-test/demo-app/src/main/java/io/opentelemetry/android/demo/OtelDemoApplication.kt#L35), where I also made the `GlobalAttributeSupplierImpl` instance available statically.

Once everything was set up, I modified the app's first screen to look like the following:

<img src="https://github.com/user-attachments/assets/e4b68a17-0bb5-4afc-b5a7-d4c8da712d1f"  width="300"/>

I've added those 3 buttons, "Send span", "Send log" and "Update global attrs". The action for "Send log" is [here](https://github.com/LikeTheSalad/opentelemetry-android/blob/global-attrs-test/demo-app/src/main/java/io/opentelemetry/android/demo/MainActivity.kt#L96) and the action for "Update global attrs" is [here](https://github.com/LikeTheSalad/opentelemetry-android/blob/global-attrs-test/demo-app/src/main/java/io/opentelemetry/android/demo/MainActivity.kt#L105) for reference.

For my tests I used the Elastic stack, although it should all work with any other vendor. If you would like to test it, you should set your vendor's endpoint params [here](https://github.com/LikeTheSalad/opentelemetry-android/blob/global-attrs-test/demo-app/src/main/java/io/opentelemetry/android/demo/OtelDemoApplication.kt#L45).

First I launched the app and clicked on "Send log", after a couple of seconds this is what I saw:

![First list of logs](https://github.com/user-attachments/assets/26f4adaf-ed5c-4fd0-948f-6fdd5038bf58)

At the top of the list, we see our log "A log body", when opening its attrs we can find the one that's set up [here](https://github.com/LikeTheSalad/opentelemetry-android/blob/global-attrs-test/demo-app/src/main/java/io/opentelemetry/android/demo/OtelDemoApplication.kt#L36) when initializing the RUM object.

![First attr details](https://github.com/user-attachments/assets/241a51e9-c4c5-44f0-a236-f59815ad937c)

It's the `dynamic_property` attr set to `unknown`, which is its initial value set [here](https://github.com/LikeTheSalad/opentelemetry-android/blob/global-attrs-test/demo-app/src/main/java/io/opentelemetry/android/demo/globalattrs/GlobalAttributeSupplierImpl.kt#L17).

Then I clicked on the "Update global attrs" button, which increases [this counter](https://github.com/LikeTheSalad/opentelemetry-android/blob/global-attrs-test/demo-app/src/main/java/io/opentelemetry/android/demo/MainActivity.kt#L35) and [adds its most recent value](https://github.com/LikeTheSalad/opentelemetry-android/blob/global-attrs-test/demo-app/src/main/java/io/opentelemetry/android/demo/MainActivity.kt#L108) to the `dynamic_property` attr.

Then I clicked on "Send log" again, and after a few seconds I opened the newest log at the top:

![Logs after change](https://github.com/user-attachments/assets/7871edd6-d6ef-4ec8-a912-c08d821a9760)

And found:

![After attrs has changed](https://github.com/user-attachments/assets/3ddfdbcc-8a9b-459e-bc35-b478dfd2c63b)

So I wasn't able to reproduce the issue. Please feel free to try it out to double-check. If you'd like you can also change my branch's code until the issue is reproducible there so that I can take another look.

I hope it helps!

**Comment by breedx-splk** [comment]
@JacekPietrasSpotOn have you had a chance to look at this again? I also tried just now and couldn't reproduce this...

I do see something that's potentially a source of confusion/error, though. In the code given above, @JacekPietrasSpotOn has this:
```
val config = OtelRumConfig()
            .setGlobalAttributes { attributeSupplier.get() }
            // ...
```

Now, I think that's fine -- although `setGlobalAttributes` is overloaded and can take either `Attributes` or `Supplier<Attributes>`, the fact that it's using the closure syntax `{ ... }` means that it should be calling `setAttributes(Supplier<Attributes>)` with an anonymous `Supplier` that always just returns the value returned from calling `get()` on the `attributesSupplier`....which is indeed what happens when I test this. Every span causes this to get re-invoked.

I think this is unnecessarily complicated and could be simplified to just

```
val config = OtelRumConfig()
            .setGlobalAttributes(attributesSupplier)
            // ...

```

less code, easier to reason about. But it would be a VERY EASY MISTAKE to just call `.setGlobalAttributes(attributesSupplier.get())` instead....and that would definitely cause the same attributes to appear for every span. @JacekPietrasSpotOn can you confirm that this isn't what you might accidentally be doing?

Anyway, a simply way for us to remedy this potentially confusing situation is to eliminate the method overload and rename `setGlobalAttributes(Supplier<>)` to `setGlobalAttributesSupplier(Supplier<>)`. I don't feel _that_ strongly about it, so please if anyone reading this likes this idea, feel free to open an issue. 👍🏻

**Comment by JacekPietrasSpotOn** [comment]
Hello @breedx-splk @LikeTheSalad,
Thank you for your input! 
The problem is not with the way of setting `AttributeSupplier` but with the need for definition of keys before the creation of `OtelRumConfig`. In our use case, we don't know all the keys at that point. Using the example from a branch created by @LikeTheSalad :

The working solution:
```kotlin
globalAttrs = GlobalAttributeSupplierImpl()
globalAttrs.createInitialAttributesWithKey(listOf("dynamic_property"))
val config =
    OtelRumConfig()
        .setGlobalAttributes(globalAttrs)
        .setDiskBufferingConfiguration(diskBufferingConfig)
// ...
OtelDemoApplication.globalAttrs.update(
    "dynamic_property",
    "Has changed ${(++attrChanges)} time(s)"
)
```

The expected:
```kotlin
globalAttrs = GlobalAttributeSupplierImpl()
// globalAttrs.createInitialAttributesWithKey(listOf("dynamic_property")) // do not require to define it
val config =
    OtelRumConfig()
        .setGlobalAttributes(globalAttrs)
        .setDiskBufferingConfiguration(diskBufferingConfig)
// ...
OtelDemoApplication.globalAttrs.update(
    "dynamic_property",
    "Has changed ${(++attrChanges)} time(s)"
)
```

As the workaround, we are guessing all possible dynamic properties, but It would be much better to not need to.

**Comment by breedx-splk** [comment]
> The problem is not with the way of setting `AttributeSupplier` but with the need for definition of keys before the creation of `OtelRumConfig`.

I don't think this is true. The thing returned from the `Supplier<Attributes>` may return an entirely different, disjoint set of attributes on each call. What makes you think that the keys have to be known beforehand?

**Comment by JacekPietrasSpotOn** [comment]
I will rephrase it. 
Our implementation problem was not with the way we set AttributeSupplier. The same supplier is passed in both scenarios:
![image](https://github.com/user-attachments/assets/a77cf41e-4bc2-4964-8646-295c2c94239d)

The difference that made it work correctly is the definition of keys before creating OtelRumConfig, as in the example shared by @LikeTheSalad. Without it, none of the global attributes are added.

Our current implementation works correctly, but it's not perfect. Our problem now is that all possible keys with some default value need to be known and set at the start of the application, before the creation of `OtelRumConfig`. They cannot be added dynamically. Only the value of an already existing attribute can be dynamically updated.

**Comment by breedx-splk** [comment]
Knowing the keys in advance is absolutely NOT a requirement for this to work correctly. I'm not sure why you're struggling with this, but I fear you might simply have a mistake in your implementation, which you haven't yet shared with us. If you can show us what the implementation of `GlobalAttributeSupplierImpl` is, we _might_ be able to spot a problem...but without it, we can only speculate...and are unable to reproduce what you are seeing, in spite of 3 attempts now.

Please have a look at [the small change I made](https://github.com/breedx-splk/opentelemetry-android/commit/38051b7135a71e2e609de76bce4d6ea8c1d1beeb) to the demo-app [in this branch](https://github.com/breedx-splk/opentelemetry-android/tree/dynamic_global_attributes). That simply generates a new, randomly named attributes in a new Attributes instance on each `get()` invocation. Try it yourself. It will create some spans that have attributes (jaeger calls them tags) that look like this:

<img width="429" alt="image" src="https://github.com/user-attachments/assets/35a826fd-9fab-4f7c-aaeb-9c6784ea97d7" />
<img width="444" alt="image" src="https://github.com/user-attachments/assets/a4a453c7-9690-4788-96ec-2f8e7845bc2e" />

Note that both the key and the value are dynamic and change with each invocation.

**Comment by JacekPietrasSpotOn** [comment]
Hello @breedx-splk 
I'm confused, today I cannot replicate the issue. Thank you for being so patient!
I will ask @jpmuedano for additional confirmation that it is working.

There is `GlobalAttributeSupplier` (skipping Impl and interface)
```
internal class GlobalAttributeSupplier : Supplier<Attributes> {

    private var attributes: Attributes = Attributes.empty()

    override fun get(): Attributes = attributes

    // not used now
    fun defineAttributeKeys(defaultKeys: Map<String, Any>) {
        attributes = defaultKeys.toAttributes()
    }

    fun update(key: String, value: Any) {
        attributes = attributes.toBuilder()
            .put(key, value)
            .build()
    }

    private fun Map<String, Any>.toAttributes(): Attributes =
        Attributes.builder()
            .putAll(this)
            .build()

    private fun AttributesBuilder.putAll(map: Map<String, Any>): AttributesBuilder {
        map.forEach { (key, value) ->
            put(key, value)
        }
        return this
    }

    private fun AttributesBuilder.put(key: String, value: Any): AttributesBuilder =
        when (value) {
            is String -> put(key, value)
            is Boolean -> put(key, value)
            is Int -> put(key, value.toLong())
            is Short -> put(key, value.toLong())
            is Byte -> put(key, value.toLong())
            is Long -> put(key, value)
            is Float -> put(key, value.toDouble())
            is Double -> put(key, value)
            else -> put(key, value.toString())
        }
}
```

**Comment by breedx-splk** [comment]
One thing that comes immediately to mind is that this class doesn't do any synchronization and therefore is not thread-safe. As such, if this class is updated (via `update()`) on one thread and the read from a different thread, the reading thread is not guaranteed to see the updated value. That might have caused the behavior you were seeing before, and also can lead to inconsistent results.

**Comment by jpmuedano** [comment]
Hello  @breedx-splk & @JacekPietrasSpotOn 
I was able to ran tests successfully on our side, and appreciate all the help & clarification. 
I am also confused and can not reproduce any longer, but good news that the keys are not required to be known in advance. 

> But it would be a VERY EASY MISTAKE to just call .setGlobalAttributes(attributesSupplier.get()) instead....and that would definitely cause the same attributes to appear for every span

My guess is that at some point during initial implementation & testing is that the above is the mistake that I made, and eventually added the following restriction in the supplier:
```
    override fun update(key: String, value: Any) {
        if (isNotDefinedKey(key, value)) {
            if (isDebug) {
                throw IllegalGlobalAttribute(key)
            } else {
                return
            }
        }
        attributes = attributes.toBuilder()
            .put(key, value)
            .build()
    }

    private class IllegalGlobalAttribute(key: String) :
        Exception("Attribute key:[$key] was not set in globalAttributes, or has wrong value type")
```

 which prevented us from evaluating further, even if we did not stick with calling `.setGlobalAttributes(attributesSupplier.get())`, and using `.setGlobalAttributes(attributesSupplier)` in the end. 

 > Anyway, a simply way for us to remedy this potentially confusing situation is to eliminate the method overload and rename setGlobalAttributes(Supplier<>) to setGlobalAttributesSupplier(Supplier<>). I don't feel that strongly about it, so please if anyone reading this likes this idea, feel free to open an issue. 👍🏻

I don't believe it is necessary, and this closed issue should be a reference for others. 

Thank you 👯
