### ISSUE TITLE
Centralizing okhttp byte-buddy dependencies in a shared project

### ISSUE THREAD

**Issue by ddas09** [open-telemetry/opentelemetry-android#712]
Hi Team,

I have the following scenario:
I have an Android app that uses a shared common library project. Currently, I’m adding the Byte Buddy plugin and OkHttp dependencies directly to the app, following the [OpenTelemetry OkHttp docs](https://github.com/open-telemetry/opentelemetry-android/tree/main/instrumentation/okhttp/okhttp-3.0), to enable OkHttp auto-instrumentation.

However, when I tried adding these dependencies to the gradle file of the shared common library (since the Android app uses it), the OkHttp auto-instrumentation didn’t work.

Is it possible to centralize these dependencies in the shared library project while still having the OkHttp auto-instrumentation work?

Any insights would be greatly appreciated!

**Comment by LikeTheSalad** [comment]
Hi @ddas09 

From what I understood it seems like you'd like to have a single place to define all your shared dependencies, the problem with bytebuddy dependencies (the ones defined with the `byteBuddy` namespace) is that they are special because they are only used during the app's compilation process and are not transitive, they are more similar to `kapt/ksp/annotationProcessor` dependencies if you will, so they must be defined within their target project directly to make the compilation process work properly.

However, there might still be a way for you to define them in a single, shared place to avoid repeating stuff across projects, by using [pre-compiled script plugins](https://docs.gradle.org/current/userguide/implementing_gradle_plugins_precompiled.html). You can define a "convention plugin" for all your application submodules to use where you'd define things such as the bytebuddy plugin alongside its dependencies (such as the okhttp one for example) and it _should_ work (I haven't tested it, though it should work). We make use of pre-compiled plugins in this project to create shared conventions across modules, you can take a look at one example [here](https://github.com/open-telemetry/opentelemetry-android/blob/e5138f41f1c7381e207f0bc19caa3fd15e0a21c0/buildSrc/src/main/kotlin/otel.android-app-conventions.gradle.kts#L4) in case it helps to get an idea of how they can be used.

**Comment by ddas09** [comment]
Thanks @LikeTheSalad, I will give it a try!
